apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: enrolment-form
  annotations:
    external-dns.alpha.kubernetes.io/target: sokh.duckdns.org
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - enroll.agd.org.au
      secretName: agd-tls
  rules:
    - host: enroll.agd.org.au
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: enrolment-form
                port:
                  number: 80
