apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ./resources/external-secret.yaml

helmCharts:
- name: nocodb
  releaseName: nocodb
  namespace: persistence
  version: 1.4.0
  repo: https://zekker6.github.io/helm-charts
  valuesFile: values.yaml
