apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

helmCharts:
- name: postgresql
  releaseName: postgresql
  namespace: persistence
  version: 18.1.11
  repo: oci://registry-1.docker.io/bitnamicharts
  valuesFile: values.yaml
  additionalValuesFiles:
    - values.sops.yaml
